# Generated by Django 4.0.3 on 2022-05-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sensor_register',
            fields=[
                ('register_no', models.AutoField(primary_key=True, serialize=False)),
                ('device_no', models.IntegerField()),
                ('sen_longitude', models.DecimalField(decimal_places=6, default=1.0, max_digits=7)),
                ('sen_latitude', models.DecimalField(decimal_places=6, default=1.0, max_digits=7)),
                ('date', models.DateField(auto_now=True)),
                ('time_zone', models.TimeField(auto_now=True)),
                ('sen_type', models.CharField(max_length=10)),
                ('plant_name', models.CharField(max_length=20)),
                ('measurement', models.IntegerField()),
                ('plot_id', models.IntegerField()),
                ('crop', models.CharField(default=False, max_length=50)),
            ],
        ),
    ]
