# Generated by Django 4.0.3 on 2022-05-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor_register',
            name='sensor_value',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='sensor_register',
            name='value_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sensor_register',
            name='value_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
