# Generated by Django 4.0.3 on 2022-05-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_sensor_register_sensor_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor_register',
            name='value_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='sensor_register',
            name='value_time',
            field=models.TimeField(blank=True),
        ),
    ]
