# Generated by Django 4.0.3 on 2022-05-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_alter_sensor_register_value_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name2', models.CharField(max_length=20)),
                ('sensor_value2', models.IntegerField()),
                ('value_date2', models.DateField(auto_now_add=True)),
                ('value_time2', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
