# Generated by Django 4.0.3 on 2022-05-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0004_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor_register',
            name='value_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sensor_register',
            name='value_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
